name: "DEPBADGE"
author: "Eugen Hildt"
description: "Generates badges.json and BADGES_README.md from depbadgerc.yml"

runs:
  using: "node24"
  main: "dist/index.js"

branding:
  icon: "tag"
  color: "blue"
